name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ–¥ï¸ Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: ğŸ§¶ Install
      run: yarn install
    - name: Copy config
      run: cp config.sample.json config.json
    - name: ğŸ”¨ Build
      run: yarn build
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ğŸ–¥ï¸ Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: ğŸ§¶ Install
      run: yarn install
    - name: ğŸ“‡ Lint
      run: yarn lint
